#execution_env=remote
execution_env=local
appURL=https://demo.opencart.com/en-gb
#https://demo.opencart.com/en-gb?route=account/account&customer_token=bef391d01e54994b79f633bd5bpublic 
	
email=sde123@gmail.com
password=sde123
searchProductName=iphone